=== smartstore/Smartstore/src/Smartstore.Modules/module.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Schema for module JSON file format",
  "type": "object",
  "required": [ "FriendlyName", "SystemName", "Version" ],
  "properties": {
    "FriendlyName": {
      "type": "string",
      "description": "English (unlocalized) friendly name."
    },
    "Description": {
      "type": "string",
      "description": "English (unlocalized) description."
    },
    "SystemName": {
      "type": "string",
      "description": "Module system name (usually the assembly name without extension)."
    },
    "Icon": {
      "type": "string",
      "description": "Optional icon address with rendering modifiers (e.g. hi:cart?color=#f90). Replaces icon.svg or icon.png; provider-specific image files take precedence."
    },
    "Theme": {
      "type": "string",
      "description": "Theme name (if the module is a theme companion). On build a symbolic link will be created in /Themes/[Theme] to /Modules/[Module]."
    },
    "Author": {
      "type": "string",
      "description": "Author name."
    },
    "ProjectUrl": {
      "type": "string",
      "description": "Link to project's or author's homepage."
    },
    "Tags": {
      "type": "string",
      "description": "Comma-separated tags."
    },
    "Version": {
      "type": "string",
      "description": "The current version of module, e.g. '2.1.0'."
    },
    "MinAppVersion": {
      "type": "string",
      "description": "The minimum compatible application version, e.g. '5.0.0'."
    },
    "ResourceRootKey": {
      "type": "string",
      "description": "Root key for language resources."
    },
    "AssemblyName": {
      "type": "string",
      "description": "Optional assembly name. By default '{SystemName}.dll' is assumed to be the assembly name."
    },
    "Order": {
      "type": "integer",
      "description": "The display order in the module manager group."
    },
    "PrivateReferences": {
      "type": "array",
      "description": "Optional array of private dependency package names that this module references. By default, referenced packages are not copied to the module's output directory because it is assumed that the application core references them already. Any module private package should be listed here (including the complete dependency chain).",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "DependsOn": {
      "type": "array",
      "description": "Optional array of module system names that this module depends on.",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "Group": {
      "description": "Conceptual group name. Used to visually categorize module in module listings.",
      "enum": [
        "Admin",
        "Marketing",
        "Payment",
        "Shipping",
        "Tax",
        "Analytics",
        "CMS",
        "Media",
        "SEO",
        "Data",
        "Globalization",
        "Api",
        "Mobile",
        "Social",
        "Security",
        "Developer",
        "Sales",
        "Design",
        "Performance",
        "B2B",
        "Storefront",
        "Law",
        "AI"
      ]
    }
  }
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.Google.MerchantCenter/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Marketing",
  "SystemName": "Smartstore.Google.MerchantCenter",
  "FriendlyName": "Google Merchant Center (GMC) feed",
  "Description": "Exports products in the Google Merchant Center feed format.",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Feed.Froogle",
  "ProjectUrl": "http://community.smartstore.com/marketplace/file/37-google-merchant-center-gmc-feed/"
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.Google.Auth/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Security",
  "SystemName": "Smartstore.Google.Auth",
  "FriendlyName": "Google Authentication",
  "Description": "Enables login with Google account.",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Author": "SmartStore AG",
  "Order": 1,
  "ResourceRootKey": "Plugins.Smartstore.Google.Auth",
  "PrivateReferences": [
    "Microsoft.AspNetCore.Authentication.Google"
  ]
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.PayPal/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Payment",
  "SystemName": "Smartstore.PayPal",
  "FriendlyName": "Smartstore.PayPal",
  "Description": "Enables payments with PayPal",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Smartstore.PayPal",
  "ProjectUrl": "http://community.smartstore.com/marketplace/file/29-paypal-payment-plugins/"
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.AmazonPay/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Payment",
  "SystemName": "Smartstore.AmazonPay",
  "FriendlyName": "Amazon Pay",
  "Description": "Login and Pay with Amazon",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Payments.AmazonPay",
  "ProjectUrl": "http://community.smartstore.com/marketplace/file/11-amazon-payments-plugin/",
  "PrivateReferences": [ "Amazon.Pay.API.SDK" ]
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.Stripe/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Payment",
  "SystemName": "Smartstore.Stripe",
  "FriendlyName": "Stripe",
  "Description": "Extends the store with Stripe payment.",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Smartstore.Stripe",
  "PrivateReferences": [ "Stripe.net" ]
}
