=== smartstore/Smartstore/src/Smartstore.Modules/module.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Schema for module JSON file format",
  "type": "object",
  "required": [ "FriendlyName", "SystemName", "Version" ],
  "properties": {
    "FriendlyName": {
      "type": "string",
      "description": "English (unlocalized) friendly name."
    },
    "Description": {
      "type": "string",
      "description": "English (unlocalized) description."
    },
    "SystemName": {
      "type": "string",
      "description": "Module system name (usually the assembly name without extension)."
    },
    "Icon": {
      "type": "string",
      "description": "Optional icon address with rendering modifiers (e.g. hi:cart?color=#f90). Replaces icon.svg or icon.png; provider-specific image files take precedence."
    },
    "Theme": {
      "type": "string",
      "description": "Theme name (if the module is a theme companion). On build a symbolic link will be created in /Themes/[Theme] to /Modules/[Module]."
    },
    "Author": {
      "type": "string",
      "description": "Author name."
    },
    "ProjectUrl": {
      "type": "string",
      "description": "Link to project's or author's homepage."
    },
    "Tags": {
      "type": "string",
      "description": "Comma-separated tags."
    },
    "Version": {
      "type": "string",
      "description": "The current version of module, e.g. '2.1.0'."
    },
    "MinAppVersion": {
      "type": "string",
      "description": "The minimum compatible application version, e.g. '5.0.0'."
    },
    "ResourceRootKey": {
      "type": "string",
      "description": "Root key for language resources."
    },
    "AssemblyName": {
      "type": "string",
      "description": "Optional assembly name. By default '{SystemName}.dll' is assumed to be the assembly name."
    },
    "Order": {
      "type": "integer",
      "description": "The display order in the module manager group."
    },
    "PrivateReferences": {
      "type": "array",
      "description": "Optional array of private dependency package names that this module references. By default, referenced packages are not copied to the module's output directory because it is assumed that the application core references them already. Any module private package should be listed here (including the complete dependency chain).",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "DependsOn": {
      "type": "array",
      "description": "Optional array of module system names that this module depends on.",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "Group": {
      "description": "Conceptual group name. Used to visually categorize module in module listings.",
      "enum": [
        "Admin",
        "Marketing",
        "Payment",
        "Shipping",
        "Tax",
        "Analytics",
        "CMS",
        "Media",
        "SEO",
        "Data",
        "Globalization",
        "Api",
        "Mobile",
        "Social",
        "Security",
        "Developer",
        "Sales",
        "Design",
        "Performance",
        "B2B",
        "Storefront",
        "Law",
        "AI"
      ]
    }
  }
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.OfflinePayment/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Payment",
  "SystemName": "Smartstore.OfflinePayment",
  "Icon": "hi:cashier-02?color=#00695C",
  "FriendlyName": "Adds offline payment methods to the store",
  "Description": "",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Author": "SmartStore AG",
  "Order": 1,
  "ResourceRootKey": "Plugins.Smartstore.OfflinePayment"
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.Microsoft.Auth/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Security",
  "SystemName": "Smartstore.Microsoft.Auth",
  "FriendlyName": "Microsoft Authentication",
  "Description": "Enables login with Microsoft account.",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Author": "SmartStore AG",
  "Order": 1,
  "ResourceRootKey": "Plugins.Smartstore.Microsoft.Auth",
  "PrivateReferences": [
    "Microsoft.AspNetCore.Authentication.MicrosoftAccount"
  ]
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.Twitter.Auth/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Security",
  "SystemName": "Smartstore.Twitter.Auth",
  "FriendlyName": "X Authentication",
  "Description": "Enables login with X account.",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Author": "SmartStore AG",
  "Order": 1,
  "ResourceRootKey": "Plugins.ExternalAuth.Twitter",
  "PrivateReferences": [
    "Microsoft.AspNetCore.Authentication.Twitter"
  ]
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.ShippingByWeight/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Shipping",
  "SystemName": "Smartstore.ShippingByWeight",
  "Icon": "hi:delivery-truck-01?color=#D84315",
  "FriendlyName": "Shipping by weight",
  "Description": "Provides shipping methods with computation based on weight.",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Shipping.ByWeight",
  "ProjectUrl": ""
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.WebApi/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Developer",
  "SystemName": "Smartstore.WebApi",
  "Icon": "hi:api?color=#283593",
  "FriendlyName": "Smartstore Web API",
  "Description": "Provides RESTful data exchange with Smartstore based on OData",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Api.WebApi",
  "ProjectUrl": "http://community.smartstore.com/marketplace/file/27-smartstorenet-web-api/",
  "PrivateReferences": [
    "Microsoft.OpenApi",
    "Swashbuckle.AspNetCore.Swagger",
    "Swashbuckle.AspNetCore.SwaggerGen",
    "Swashbuckle.AspNetCore.SwaggerUI"
  ]
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.Facebook.Auth/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Security",
  "SystemName": "Smartstore.Facebook.Auth",
  "Icon": "fa:facebook/b?color=#0866FF",
  "FriendlyName": "Facebook Authentication",
  "Description": "Enables login with Facebook account.",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Author": "SmartStore AG",
  "Order": 1,
  "ResourceRootKey": "Plugins.ExternalAuth.Facebook",
  "PrivateReferences": [
    "Microsoft.AspNetCore.Authentication.Facebook"
  ]
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.Clickatell/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Mobile",
  "SystemName": "Smartstore.Clickatell",
  "FriendlyName": "Clickatell SMS Provider",
  "Description": "Sends order notifications to shop administrator via SMS.",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Sms.Clickatell"
}

=== smartstore/Smartstore/src/Smartstore.Modules/Smartstore.Google.Analytics/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Analytics",
  "SystemName": "Smartstore.Google.Analytics",
  "FriendlyName": "Google Analytics",
  "Description": "Adds Google Analytics tracking scripts to the shop.",
  "Version": "6.4.0",
  "MinAppVersion": "6.4.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Widgets.GoogleAnalytics",
  "ProjectUrl": "http://community.smartstore.com/marketplace/file/25-google-analytics/"
}
